#!/usr/bin/env tsx
import { existsSync, readdirSync, readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";

interface Options {
  campaign: string;
  check: boolean;
}

function parseArgs(argv: string[]): Options {
  let campaign = "";
  let check = false;

  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--campaign" && i + 1 < argv.length) {
      campaign = argv[i + 1];
      i++;
    } else if (argv[i] === "--check") {
      check = true;
    }
  }

  if (!campaign) {
    process.stderr.write(
      "ERROR: 请指定活动名称：pnpm gen-integration-skel --campaign <campaign-name>\n",
    );
    process.exit(2);
  }

  return { campaign, check };
}

interface SectionInfo {
  name: string;
  dataSource: string;
  imageKeys: string[];
}

function readFileSafe(path: string): string | null {
  try {
    return readFileSync(path, "utf-8");
  } catch {
    return null;
  }
}

function extractDynamicSections(structureContent: string): SectionInfo[] {
  const sections: SectionInfo[] = [];

  // Parse Section table rows to find dynamic data sections
  const tableRegex =
    /\| (\d+) \| (\w+Section) \| .+? \| (动态数据) \|/g;
  let match;
  while ((match = tableRegex.exec(structureContent)) !== null) {
    sections.push({ name: match[2], dataSource: match[3], imageKeys: [] });
  }

  // Also try to find Image Asset Inventory entries for each section
  for (const section of sections) {
    const imageRegex = new RegExp(
      `\\|\\s*(\\w+)\\s*\\|\\s*${section.name}\\s*\\|`,
      "g",
    );
    let imgMatch;
    while ((imgMatch = imageRegex.exec(structureContent)) !== null) {
      section.imageKeys.push(imgMatch[1]);
    }
  }

  return sections;
}

function generateAdapterSkel(sectionName: string, imageKeys: string[]): string {
  const lines: string[] = [];
  lines.push(
    `// @generated by gen-integration-skel — ${new Date().toISOString()}`,
  );
  lines.push(`// 来源: apps/<campaign>/.feedback/structure.md`);
  lines.push(`// Section: ${sectionName}, 数据来源: 动态数据`);
  lines.push(`// TODO: 补充 DTO → SectionState 映射逻辑`);
  lines.push(``);
  lines.push(
    `import type { SectionState } from '../../store';`,
  );
  lines.push(
    `import type { ${sectionName}Content } from '../../designer/sections/${sectionName}/types';`,
  );
  lines.push(``);
  lines.push(
    `export function adapt${sectionName}(dto: unknown): SectionState<${sectionName}Content> {`,
  );
  if (imageKeys.length > 0) {
    lines.push(`  // 图片字段需要映射: ${imageKeys.join(", ")}`);
  }
  lines.push(`  // TODO: 映射 DTO 字段到 ${sectionName}Content`);
  lines.push(
    `  throw new Error('Adapter for ${sectionName} not implemented');`,
  );
  lines.push(`}`);
  return lines.join("\n");
}

function generateContractSkel(sectionName: string): string {
  const lines: string[] = [];
  lines.push(
    `// @generated by gen-integration-skel — ${new Date().toISOString()}`,
  );
  lines.push(`// 来源: apps/<campaign>/.feedback/structure.md`);
  lines.push(`// Section: ${sectionName}`);
  lines.push(
    `// TODO: 声明该 Section 需要的展示语义（非 DTO 字段，非 API 路径）`,
  );
  lines.push(``);
  lines.push(`import type { ${sectionName}Content } from '../designer/sections/${sectionName}/types';`);
  lines.push(``);
  lines.push(`export interface ${sectionName}Contract {`);
  lines.push(`  // TODO: 定义展示端所需字段`);
  lines.push(`  // 示例: displayName: string;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(
    `export function validate${sectionName}Contract(`,
  );
  lines.push(`  _contract: ${sectionName}Contract,`);
  lines.push(`): ${sectionName}Content {`);
  lines.push(`  // TODO: contract → Content 映射`);
  lines.push(
    `  throw new Error('Contract validation for ${sectionName} not implemented');`,
  );
  lines.push(`}`);

  return lines.join("\n");
}

function main(argv = process.argv.slice(2)): void {
  const { campaign, check } = parseArgs(argv);
  const rootDir = process.cwd();
  const appSrc = join(rootDir, "apps", campaign, "src");
  const feedbackDir = join(rootDir, "apps", campaign, ".feedback");
  const structurePath = join(feedbackDir, "structure.md");

  if (!existsSync(structurePath)) {
    process.stderr.write(
      `ERROR: structure.md 不存在: ${structurePath}\n请先完成结构规划阶段\n`,
    );
    process.exit(2);
  }

  const structureContent = readFileSafe(structurePath)!;
  const dynamicSections = extractDynamicSections(structureContent);

  if (dynamicSections.length === 0) {
    process.stdout.write(
      "INFO: 未找到动态数据 Section，无需生成 integration 骨架\n",
    );
    process.exit(0);
  }

  if (check) {
    // Check mode: verify skeletons exist for all dynamic sections
    const missing: string[] = [];
    const adaptersDir = join(appSrc, "integrations", "adapters");
    const contractsDir = join(appSrc, "integrations", "contracts");

    for (const section of dynamicSections) {
      const adapterPath = join(adaptersDir, `${section.name}Adapter.ts`);
      if (!existsSync(adapterPath)) {
        missing.push(`adapters/${section.name}Adapter.ts`);
      }
      const contractPath = join(contractsDir, `${section.name}.contract.ts`);
      if (!existsSync(contractPath)) {
        missing.push(`contracts/${section.name}.contract.ts`);
      }
    }

    if (missing.length > 0) {
      process.stdout.write(
        `INFO: 缺少 integration 骨架文件 (${missing.length}):\n`,
      );
      for (const m of missing) {
        process.stdout.write(`  - ${m}\n`);
      }
      process.stdout.write(
        `建议运行: pnpm gen-integration-skel --campaign ${campaign}\n`,
      );
    } else {
      process.stdout.write(
        `OK: 所有动态 Section 已有 integration 骨架 (${dynamicSections.length} sections)\n`,
      );
    }
    process.exit(missing.length > 0 ? 0 : 0);
  }

  // Generate mode
  const adaptersDir = join(appSrc, "integrations", "adapters");
  const contractsDir = join(appSrc, "integrations", "contracts");
  const fixturesDir = join(appSrc, "integrations", "fixtures");

  mkdirSync(adaptersDir, { recursive: true });
  mkdirSync(contractsDir, { recursive: true });
  mkdirSync(fixturesDir, { recursive: true });

  for (const section of dynamicSections) {
    const adapterPath = join(adaptersDir, `${section.name}Adapter.ts`);
    const contractPath = join(contractsDir, `${section.name}.contract.ts`);
    const fixturePath = join(fixturesDir, `${section.name}.fixture.json`);

    if (!existsSync(adapterPath)) {
      writeFileSync(
        adapterPath,
        generateAdapterSkel(section.name, section.imageKeys),
      );
      process.stdout.write(`CREATED adapters/${section.name}Adapter.ts\n`);
    } else {
      process.stdout.write(`SKIP adapters/${section.name}Adapter.ts (已存在)\n`);
    }

    if (!existsSync(contractPath)) {
      writeFileSync(contractPath, generateContractSkel(section.name));
      process.stdout.write(`CREATED contracts/${section.name}.contract.ts\n`);
    } else {
      process.stdout.write(`SKIP contracts/${section.name}.contract.ts (已存在)\n`);
    }

    if (!existsSync(fixturePath)) {
      writeFileSync(
        fixturePath,
        JSON.stringify(
          {
            _generated: `gen-integration-skel — ${new Date().toISOString()}`,
            _section: section.name,
            _todo: "替换为真实 mock 数据",
          },
          null,
          2,
        ),
      );
      process.stdout.write(`CREATED fixtures/${section.name}.fixture.json\n`);
    } else {
      process.stdout.write(`SKIP fixtures/${section.name}.fixture.json (已存在)\n`);
    }
  }

  process.stdout.write(
    `\n完成: 为 ${dynamicSections.length} 个动态 Section 生成了 integration 骨架\n`,
  );
  process.stdout.write(
    `  - adapters/: ${dynamicSections.length} 文件\n`,
  );
  process.stdout.write(
    `  - contracts/: ${dynamicSections.length} 文件\n`,
  );
  process.stdout.write(
    `  - fixtures/: ${dynamicSections.length} 文件\n`,
  );
}

main();
